### ISSUE TITLE
implement canon for `const_arrayvec`

### ISSUE THREAD

**Issue by ZER0** [dusk-network/canonical#35]
In order to port microkelvin to `no_std` we need to implement canon also for `const_arrayvec`.

**Comment by krl** [comment]
I need more motivation why this is needed, i don't think we should pull in dependencies lightly, since this is such a foundational crate.

**Comment by ZER0** [comment]
As discussed on rocket chat, I'm going to close as `wontfix` for the time being. The motivation was to port microkelvin's tests, that I thought reflects our common scenarios, that uses vectors. Apparently this is not the case (at least for now), so I implemented the canon for arrayvec in microkelvin's test via newtype pattern.

If we notice we need to have canon implemented for arrayvec also outside tests, we're going to reopen this issue.
