### ISSUE TITLE
Canonical derive - conflict with dusk-bytes over `syn` version

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/canonical#64]
`canonical_derive` is using `1.0.17` and `dusk-bytes` is using `1.0.58`

They are conflicting when implemented over the same crate. Both should not specify the `patch` version

**Comment by vlopes11** [comment]
https://github.com/dusk-network/dusk-bytes/issues/2

**Comment by ZER0** [comment]
This is solved by https://github.com/dusk-network/dusk-bytes/issues/2
