### ISSUE TITLE
BytesSource and BytesSink should not require a `Store`

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/canonical#71]
Bytes source operates only with the provided `buffer`. The `store` is passed only for further querying, and imposes the need to own a reference to a `Store`.

This causes some anomalies to the dependencies of canonical such as `dusk_abi::Transaction` requiring a reference to a store to cast to a given type that implements `Canon` when the `Store` is actually never accessed - the bytes of the owned `Vec<u8>` contains all the required data.

https://github.com/dusk-network/canonical/blob/12062d2c91c4dd48337d8630cb0e200290a4c422/canon/src/store.rs#L161-L192

**Comment by krl** [comment]
This is required because of support for recursive structures. Have a look at https://github.com/dusk-network/canonical/blob/master/canon/src/repr.rs#L82

While it might be possible to get rid of the S generic, that would require another way of getting the store reference to the Repr.
