### ISSUE TITLE
Add tags retroactively and create the CHANGELOG from the initial commit

### ISSUE THREAD

**Issue by ZER0** [dusk-network/canonical#79]
Currently there is no CHANGELOG in Canonical, neither any tag related to its versioning.

Since our current stack is heavily based on Canonical, we should documents all the changes happened until now, and mark the proper commits for the versioning retroactively; as it was done for [dusk-abi](https://github.com/dusk-network/dusk-abi/blob/master/CHANGELOG.md) for example:
1. Take the history of `Cargo.toml` to identify the changes in term of versioning
2. keep trace of the commit where the version was bump, and add `tag` them
3. Gets the commits between each versions, and rephrase the commit message to be inline with the [changelog format](https://keepachangelog.com/en/1.0.0/): basically each "changes" should start with either `Add`, `Change`, `Fix`, `Test`, `Remove` or `Deprecate`: also `Replace`, `Rename` and `Update` can be used (as alias of `Change`).

Linking issues is okay but not mandatory; check again [dusk-abi](https://github.com/dusk-network/dusk-abi/blob/master/CHANGELOG.md) for reference.

**Comment by krl** [comment]
fixed by #81
